### ISSUE TITLE
Cabal repl in a project depending on Hagl fails with "can't load .so/.DLL"

### ISSUE THREAD

**Issue by pparkkin** [walkie/Hagl#1]
I created a new project with a dependency on Hagl, and tried to open up a REPL with "cabal repl" to play around with the Hagl DSL, but the command failed with the following message:

```
Loading package Hagl-3.0.0 ... <command line>: can't load .so/.DLL for: /vagrant/.cabal-sandbox/lib/x86_64-linux-ghc-7.8.3/Hagl-3.0.0/libHSHagl-3.0.0-ghc7.8.3.so (/vagrant/.cabal-sandbox/lib/x86_64-linux-ghc-7.8.3/Hagl-3.0.0/libHSHagl-3.0.0-ghc7.8.3.so: undefined symbol: Haglzm3zi0zi0_HaglziHistory_zuscore1_info)
```

**Comment by walkie** [comment]
I realize this is an outrageously old issue, but you should now be able to open a repl with `stack ghci`.

**Comment by pparkkin** [comment]
I love it! :D
