### ISSUE TITLE
Current version fails to build with recent versions of cabal (ghc 8.0.1)

### ISSUE THREAD

**Issue by SunnyJames** [walkie/Hagl#7]
There are some apparently minor changes to the library required per @peitalin due to changes in GHC over the last couple of years.  I've gotten his forked version running without much trouble --- Is this project still maintained?  I'd like to use the library but I don't have the Haskell background to make significant modifications or maintenance.

**Comment by walkie** [comment]
Thanks for the interest!

Cleaning this project up and posting it to Hackage has been on my TODO list for some time... Unfortunately, I just don't have the bandwidth to do that right now, so sadly I guess the current status is "unmaintained".

Knowing that a handful of folks want to use it pushes it up the queue, but realistically I can't see that happening until the summer.

**Comment by walkie** [comment]
5+ years later, should at least build on recent GHC now. :-)
